### ISSUE TITLE
Problem Generating a token

### ISSUE THREAD

**Issue by GlossyRed** [eSentire-Labs/LLM-Gateway#1]
I followed the directions to install the Docker instance from the Full Stack.
I am using docker-compose version v2.20.3
I am also using a free account on openAI
I modified the docker.compose.yml with my API key formatted as : 
`LLM_API_AUTHORIZATION=my key`
The docker container spun up linked to the database and was confirmed running. 
The GUI link on port 3000 directs to google.com From the "Generate token" button. 
When using the chat box this error shows 
"The previous query failed.
Error message:
Please check your token."

**Comment by h0n33badg3rc0d3** [comment]
Assuming the API key is good (has billing added or has credits), can you try adding "Bearer " in front of the token you added in the api key? 
Made a PR here to make this more clear: https://github.com/eSentire-Labs/LLM-Gateway/pull/2

**Comment by GlossyRed** [comment]
I was able to get the app to respond after I followed your changes
